/**
 * Aligns the Apps Script and metadata version strings.
 *
 * Resolution order for the canonical version tag:
 *   1) VERSION_TAG environment variable (preferred for CI releases)
 *   2) meta.json version_tag (used when building locally from a release artifact)
 *   3) Latest git tag (fallback when neither of the above is present)
 *
 * The chosen tag is written into:
 *   - apps_script_project/Version.generated.js (referenced by Code.js at runtime)
 *   - meta.json when present (for published artifact metadata)
 *
 * This keeps a single canonical source of truth (meta.json or VERSION_TAG/git tags)
 * while avoiding hand-maintained duplicates in the Apps Script code.
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const VERSION_MODULE_PATH = path.join(
  ROOT,
  'apps_script_project',
  'Version.generated.js'
);
const META_PATH = path.join(ROOT, 'meta.json');

function safeGit(cmd) {
  try {
    return execSync(cmd, {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch (err) {
    return null;
  }
}

function readMetaVersion() {
  if (!fs.existsSync(META_PATH)) {
    return null;
  }

  try {
    const meta = JSON.parse(fs.readFileSync(META_PATH, 'utf8'));
    return meta.version_tag || null;
  } catch (err) {
    return null;
  }
}

function resolveVersionTag() {
  if (process.env.VERSION_TAG) {
    return process.env.VERSION_TAG;
  }

  const metaVersion = readMetaVersion();
  if (metaVersion) {
    return metaVersion;
  }

  const gitTag = safeGit('git describe --tags --abbrev=0');
  if (gitTag) {
    return gitTag;
  }

  throw new Error(
    'Unable to resolve version tag. Set VERSION_TAG, ensure meta.json has a version_tag, or create a git tag.'
  );
}

function writeGeneratedVersion(versionTag) {
  const banner =
    '// AUTO-GENERATED by scripts/sync-version.js. Do not edit by hand.\n';
  const contents = `${banner}const SCRIPT_VERSION = '${versionTag}';\n`;

  fs.writeFileSync(VERSION_MODULE_PATH, contents);
  console.log(
    `Wrote generated Apps Script version module to ${VERSION_MODULE_PATH}`
  );
}

function updateMetaVersion(versionTag) {
  if (!fs.existsSync(META_PATH)) {
    return;
  }

  const meta = JSON.parse(fs.readFileSync(META_PATH, 'utf8'));
  if (meta.version_tag === versionTag) {
    return;
  }

  meta.version_tag = versionTag;
  fs.writeFileSync(META_PATH, `${JSON.stringify(meta, null, 2)}\n`);
  console.log(`Aligned meta.json version_tag to ${versionTag}`);
}

function main() {
  const versionTag = resolveVersionTag();
  writeGeneratedVersion(versionTag);
  updateMetaVersion(versionTag);
}

main();
